---
- name: installing java and jenkins on master
  hosts: localhost
  become: true
  tasks: 
  - name: executing master.sh script
    script: master.sh
- name: installing docker and java on slaves
  hosts: all
  become: true
  tasks: 
  - name: executing slave.sh script
    script: slave.sh	  
